services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: ./backend/app
    container_name: web
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "8000:8000"

  nginx:
    build: ./backend/nginx
    container_name: nginx
    depends_on:
      - web
    ports:
      - "8080:80"

  bot:
    build: ./bot
    container_name: bot
    environment:
      - TELEGRAM_BOT_TOKEN=<token>
    depends_on:
      - web

volumes:
  mongo_data:
